5pm a search by ge
ucsb-cs156-f20/proj-ucsb-courses-search pull request #75
Opened 2020-12-09 05:31 UTC by kevbbn

This pull request closes #31 . This branch adds a page and form where a user can enter a ge, and start/end quarter and receive the respective information. The branch also adds a new controller for the back end to interact with the archived course repository (as well as adds respective testing for new files added in the front and back end).

2020-12-09 21:47 UTC, KobeShav requested changes
It all looks good from what I can see except for line 25 in the GeSearchController where the logger line uses the wrong class when it should be using GeSearchController.class

2020-12-09 23:58 UTC, KobeShav approved these changes
LGTM

2020-12-10 02:07 UTC, pconrad commented on javascript/src/main/pages/History/Ge.js
> +// This component displays the raw JSON returned from the API fetch, the BasicCourseTable instead displays it in a table
Generally speaking, we should take stuff like this out before merging into main.  Because time is short, I'll let it slide.

2020-12-10 02:07 UTC, pconrad approved these changes
LGTM.  I added one comment but I'm not going to make you fix it before merging.

2020-12-10 02:07 UTC, merged

2020-12-10 02:08 UTC, pconrad commented
40 pts