5pm b schedule frontend user interface
ucsb-cs156-f20/proj-ucsb-courses-search pull request #95
Opened 2020-12-12 12:16 UTC by andyyyho

This PR closes #53. This PR implements the user interface for the schedules page. It allows the user to be able to create schedules, retrieve them, and delete them. **Please ignore** the scheduleAPI files as they were already approved in another pr, but were necessary to have the schedules page function properly.

2020-12-12 12:21 UTC, yiweizhangcs approved these changes

2020-12-12 12:31 UTC, andrewhlu requested changes
It looks like your test coverage isn't complete - please fix your test coverage and re-request the staff for a review.

2020-12-13 04:56 UTC, pconrad approved these changes
LGTM.    There are three small gaps in the front-end test coverage in one file (Schedule.js), but @andyyyho and I looked at those for a few hours, and we finally decided we needed to leave that to W21.

2020-12-13 04:56 UTC, pconrad commented
50 pts

2020-12-14 20:29 UTC, merged